### ISSUE TITLE
Addresses in Checkout

### ISSUE THREAD

**Issue by irisSchaffer** [mothership-ec/cog-mothership-ecommerce#168]
I just ordered something and because I had no address yet, I had to fill out the form.
This is what the button looks like:
![screen shot 2014-02-20 at 15 57 55](https://f.cloud.github.com/assets/4313088/2219947/d99ef052-9a47-11e3-8ca3-0095808ee9c5.png)

After I clicked that button, I got this flash:
![screen shot 2014-02-20 at 15 58 12](https://f.cloud.github.com/assets/4313088/2219953/e972b3c4-9a47-11e3-8a8c-de392fbb036c.png)

I completed the order and after that ordered another item. However, my address was not saved!

1. The feedback was a bit misleading, as I thought it would save my addresses for my user and not only for the order. So I'd suggest changing the feedback and maybe the text on the button(?).
2. We should, for better UX, save the address in the checkout, if the user hasn't had one before.

**Comment by kuiche** [comment]
This is now fixed, as we have an option to save addresses.
