### ISSUE TITLE
message/cog-mothership-user no longer exist

### ISSUE THREAD

**Issue by zachjamesgreen** [mothership-ec/cog-mothership-ecommerce#233]
I have tried cloning the repository to start using it but when I install the composer dependicies composer gives me the warning
Failed to download message/cog-mothership-user from dist: The "https://api.github.com/repos/messagedigital/cog-mothership-user/zipball/3.4.0" file could not be downloaded (HTTP/1.1 404 Not Found)

Then composer tries from source and it gives me this error
[RuntimeException]                                                                                                                 
  Failed to execute git clone --no-checkout 'https://ecb7f055be9c16d897c440d411a42040f5f1fa05:***@github.com/messagedigital/cog-mothership-user.git' '/home/zach/projects/mothership/vendor/message/cog-mothership-user' && cd '/home/zach/projects/mothership/vendor/message/cog-mothership-user' && git remote add composer 'https://ecb7f055be9c16d897c440d411a42040f5f1fa05:***@github.com/messagedigital/cog-mothership-user.git' && git fetch composer 
Cloning into '/home/zach/projects/mothership/vendor/message/cog-mothership-user'...                                                
  remote: Repository not found.                                                                                                      
  fatal: repository 'https://ecb7f055be9c16d897c440d411a42040f5f1fa05:x-oauth-basic@github.com/messagedigital/cog-mothership-user.g  
  it/' not found

I think cog-mothership-user was replaced with cog-user but not updated here.

**Comment by thomasjthomasj** [comment]
Hi @zachjamesgreen 
I'm really sorry for taking so long to get back to you on this. This issue should be resolved as of version 3.0.0 of this module (when it first open sourced). You will need to set the origin and upstream to `mothership-ec/cog-mothership-ecommerce` as all the repositories have moved
